// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiPfYK1L6maLNYsUHjafBKIOUnmRuaFB0',
    appId: '1:961070263084:web:05a2f6547b8fb460285a89',
    messagingSenderId: '961070263084',
    projectId: 'billpro-21366',
    authDomain: 'billpro-21366.firebaseapp.com',
    storageBucket: 'billpro-21366.firebasestorage.app',
    measurementId: 'G-B05V5H0NWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOdg4Lv14OlC0LRMgP44suRfQdRy6LhyE',
    appId: '1:961070263084:android:0888e09285284fa5285a89',
    messagingSenderId: '961070263084',
    projectId: 'billpro-21366',
    storageBucket: 'billpro-21366.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ5Ov4VVJdKomvgEyqhRTjF64H5waepGo',
    appId: '1:961070263084:ios:f98f2307c67d1f00285a89',
    messagingSenderId: '961070263084',
    projectId: 'billpro-21366',
    storageBucket: 'billpro-21366.firebasestorage.app',
    iosBundleId: 'com.example.billpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ5Ov4VVJdKomvgEyqhRTjF64H5waepGo',
    appId: '1:961070263084:ios:f98f2307c67d1f00285a89',
    messagingSenderId: '961070263084',
    projectId: 'billpro-21366',
    storageBucket: 'billpro-21366.firebasestorage.app',
    iosBundleId: 'com.example.billpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiPfYK1L6maLNYsUHjafBKIOUnmRuaFB0',
    appId: '1:961070263084:web:f5eb7ba1c90d9409285a89',
    messagingSenderId: '961070263084',
    projectId: 'billpro-21366',
    authDomain: 'billpro-21366.firebaseapp.com',
    storageBucket: 'billpro-21366.firebasestorage.app',
    measurementId: 'G-RSVTBQEMZM',
  );
}
